# ----
# Site

title: Hurakann
description: Cloud Programming Engine.
url: https://zgbjgg.github.io/aviator-jekyll-template/
google_analytics_key:
permalink: pretty

collections:
  documentation:
    title: User's Guide
    position: 1
  api:
    title: APIs
    position: 2
gems:
  - jekyll-sitemap
  - jekyll-seo-tag

exclude:
  - readme.md
  - LICENCE

defaults:
  -
    scope:
      path: ""
    values:
      layout: default

types:
  - get
  - put
  - delete
  - post
